import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import * as S from "../styles/login";
import NavBar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function DashboardEstudante() {

  return (
    <>
      <Head>
        <title>UNIGU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar/>
      <S.Main>
        <S.Titulo>
          Efetue o login, caso não possua uma conta registre-se!
        </S.Titulo>
        <S.Container>

        </S.Container>
      </S.Main>
    </>
  )
}
