import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import * as S from "../styles/login";
import LoginForm from '@/components/LoginForm';
import RegisterForm from '@/components/RegisterForm';
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Login() {
    const [showLoginForm, setShowLoginForm] = useState(true);

    const toggleForm = () => {
      setShowLoginForm(!showLoginForm);
    }
  return (
    <>
      <Head>
        <title>UNIGU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <S.Titulo>
          Efetue o login, caso não possua uma conta registre-se!
        </S.Titulo>
        <S.Container>
        {showLoginForm ? <LoginForm /> : <RegisterForm />}
            <S.Botao onClick={toggleForm}>
                {showLoginForm ? 'Registrar' : 'Login'}
            </S.Botao>
        </S.Container>
      </S.Main>
    </>
  )
}
